server.port=${PORT:8080}

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

groq.api.url=${GROQ_API_URL:https://api.groq.com/openai/v1/chat/completions}
groq.api.key=${GROQ_API_KEY}
groq.api.key.analysis=${GROQ_API_KEY_ANALYSIS}
groq.model=${GROQ_MODEL}

spring.jpa.show-sql=false
spring.jpa.open-in-view=false
spring.jpa.hibernate.ddl-auto=update

spring.datasource.hikari.max-lifetime=300000
spring.datasource.hikari.keepalive-time=60000
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.idle-timeout=120000
spring.datasource.hikari.validation-timeout=5000

spring.datasource.hikari.maximum-pool-size=2
spring.datasource.hikari.minimum-idle=1