server.port=${PORT:8080}

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

gemini.api.url=${GEMINI_API_URL}
gemini.api.key=${GEMINI_API_KEY}

spring.jpa.show-sql=false
spring.jpa.open-in-view=false
spring.jpa.hibernate.ddl-auto=validate

spring.datasource.hikari.maximum-pool-size=2
spring.datasource.hikari.minimum-idle=1