package com.startsmart.ai.riskanalyzer.dto;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.v3.oas.annotations.media.Schema;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.LocalDateTime;
import java.util.List;
import java.util.Map;

@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class RiskAssessmentResponseDTO {

    @Schema(description = "Unique identifier for the risk assessment record")
    private Long id;

    @Schema(description = "The project ID this assessment belongs to")
    private Long projectId;

    @Schema(description = "Overall success probability (0-100) — combined across all five risk categories; equals 100 minus the overall risk score")
    private Double successProbability;

    @Schema(description = "Financial-only success probability (0-100) exactly as returned by the ML model (budget + industry). Kept distinct from the combined success probability.")
    private Double financialSuccessProbability;

    @Schema(description = "Overall risk score (0-100) — weighted combination of the five risk categories")
    private Double overallRiskScore;

    @Schema(description = "Risk level: Low, Medium, or High — derived from the weighted overall risk score")
    private String riskLevel;

    @Schema(description = "Financial risk score (0-100) — BLENDED: 60% LLM budget-adequacy judgment for this project's scope + 40% ML historical baseline. This is the headline financial figure used in risk_breakdown.financial_risk.")
    private Double financialRiskScore;

    @Schema(description = "Raw ML-only financial risk score (0-100) from the historical-data model (budget + industry), unmodified by the budget-adequacy blend. Kept for full transparency.")
    private Double mlOnlyFinancialRisk;

    @Schema(description = "LLM (Groq) budget adequacy judgment for THIS project's scope: score 0-100 (0 = budget totally inadequate, 100 = comfortably covers scope) and a reasoned explanation.")
    private BudgetAdequacyDTO budgetAdequacy;

    @Schema(description = "Top data-driven risk factors from the ML model, with feature, contribution, and direction")
    private List<MlPredictionResponseDTO.RiskFactor> topRiskFactors;

    @Schema(description = "SWOT analysis generated by the LLM, grounded on the ML baseline")
    private SwotDTO swot;

    @Schema(description = "2-3 sentence narrative explaining WHY the risk score is what it is, referencing the actual top risk factors")
    private String riskNarrative;

    @Schema(description = "Deterministically computed feasibility score (0-100) from the 7 assessment metrics")
    private Double feasibilityScore;

    @Schema(description = "Plain-language feasibility verdict from the LLM")
    private String feasibilityVerdict;

    @Schema(description = "Seven 0-100 assessment metrics from the LLM: financial_sustainability, team_capability, competitive_advantage, resource_availability, market_opportunity, execution_readiness, scalability_potential")
    private Map<String, Double> assessmentMetrics;

    @Schema(description = "Full five-category risk breakdown — financial, market, technical, operational, execution — each with {score, reason} and the data source used to derive it")
    @JsonProperty("risk_breakdown")
    private RiskBreakdownDTO riskBreakdown;

    @Schema(description = "Timestamp when the assessment was generated")
    private LocalDateTime createdAt;

    @Data
    @NoArgsConstructor
    @AllArgsConstructor
    @Builder
    public static class SwotDTO {
        private List<String> strengths;
        private List<String> weaknesses;
        private List<String> opportunities;
        private List<String> threats;
    }

    @Data
    @NoArgsConstructor
    @AllArgsConstructor
    @Builder
    @JsonIgnoreProperties(ignoreUnknown = true)
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public static class RiskBreakdownDTO {

        @JsonProperty("financial_risk")
        private RiskCategoryDTO financialRisk;

        @JsonProperty("market_risk")
        private RiskCategoryDTO marketRisk;

        @JsonProperty("technical_risk")
        private RiskCategoryDTO technicalRisk;

        @JsonProperty("operational_risk")
        private RiskCategoryDTO operationalRisk;

        @JsonProperty("execution_risk")
        private RiskCategoryDTO executionRisk;

        @JsonProperty("ml_only_financial_risk")
        private Double mlOnlyFinancialRisk;

        @JsonProperty("budget_adequacy")
        private BudgetAdequacyDTO budgetAdequacy;

        // Legacy fields: populated only when reading cached JSON written by an older app version;
        // never written on fresh generation.
        @JsonProperty("technical_risk_score")
        private Double technicalRiskScore;

        @JsonProperty("operational_risk_score")
        private Double operationalRiskScore;

        @JsonProperty("execution_risk_score")
        private Double executionRiskScore;
    }

    @Data
    @NoArgsConstructor
    @AllArgsConstructor
    @Builder
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public static class BudgetAdequacyDTO {

        @Schema(description = "0-100 — 0 = totally inadequate budget for this specific scope, 100 = budget comfortably covers this scope")
        private Integer score;

        @Schema(description = "The LLM's 1-2 sentence judgement of whether the budget is realistic for THIS specific project's scope, technical complexity, and business model")
        private String reasoning;
    }

    @Data
    @NoArgsConstructor
    @AllArgsConstructor
    @Builder
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public static class RiskCategoryDTO {

        @Schema(description = "Risk score 0-100 (higher = riskier)")
        private Double score;

        @Schema(description = "Short, project-specific reason tied to the actual submitted fields")
        private String reason;

        @Schema(description = "Data source used to derive the score: ML_MODEL (real historical data) or LLM (AI reasoning)")
        private String source;
    }
}